security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtCookieAuthenticator

    access_control:
        - { path: ^/auth/logout$, roles: ROLE_USER }

when@test:
    security:
        firewalls:
            main:
                security: true
