name: Deploy via SFTP

on:
  push:
    branches: [ "main" ] # Se déclenche à chaque push sur la branche main
  workflow_dispatch: # Permet de lancer manuellement depuis l'interface GitHub

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Préparation du fichier .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env

      - name: Déploiement des fichiers via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 115 # Port personnalisé pour le SFTP
          password: ${{ secrets.SFTP_PASSWORD }}
          # Exclure le dossier .github pour ne pas le pousser sur le serveur
          local_path: './*'
          remote_path: '/httpdocs' # Dossier racine ciblé sur le serveur
          sftp_only: true # Force l'utilisation pure du protocole SFTP sans commandes SSH
          args: '-o ConnectTimeout=5'
